"""
    Shotstack

    Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file  location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.gitbook.io/docs/guides/getting-started) documentation. There are two main API's, one for editing and generating assets (Edit API) and one for managing hosted assets (Serve API).  The Edit API base URL is: <b>https://api.shotstack.io/{version}</b>  The Serve API base URL is: <b>https://api.shotstack.io/serve/{version}</b>  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import shotstack_sdk
from shotstack_sdk.model.merge_field import MergeField
from shotstack_sdk.model.output import Output
from shotstack_sdk.model.timeline import Timeline
globals()['MergeField'] = MergeField
globals()['Output'] = Output
globals()['Timeline'] = Timeline
from shotstack_sdk.model.edit import Edit


class TestEdit(unittest.TestCase):
    """Edit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdit(self):
        """Test Edit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Edit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
