"""
    Shotstack

    Official Python SDK for the Shotstack Cloud Video Editing API

    The version of the OpenAPI document: v1
    Contact: pypi@shotstack.io
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from shotstack_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from shotstack_sdk.exceptions import ApiAttributeError


def lazy_import():
    AudioAsset
    AudioAssetVolume
    Border
    CaptionAsset
    CaptionMargin
    ChromaKey
    Crop
    HtmlAsset
    ImageAsset
    ImageToVideoAsset
    LumaAsset
    Offset
    RichCaptionActive
    RichCaptionAnimation
    RichCaptionAsset
    RichCaptionAssetFont
    RichCaptionAssetPadding
    RichTextAlignment
    RichTextAsset
    RichTextShadow
    ShapeAsset
    ShapeAssetCircle
    ShapeAssetFill
    ShapeAssetLine
    ShapeAssetRectangle
    ShapeAssetStroke
    SvgAsset
    TextAlignment
    TextAsset
    TextToImageAsset
    TextToSpeechAsset
    TitleAsset
    VideoAsset


class Asset(ModelComposed):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('type',): {
            '&#39;video&#39;': 'video',
            '&#39;image&#39;': 'image',
            '&#39;text&#39;': 'text',
            '&#39;rich-text&#39;': 'rich-text',
            '&#39;audio&#39;': 'audio',
            '&#39;luma&#39;': 'luma',
            '&#39;caption&#39;': 'caption',
            '&#39;rich-caption&#39;': 'rich-caption',
            '&#39;html&#39;': 'html',
            '&#39;title&#39;': 'title',
            '&#39;shape&#39;': 'shape',
            '&#39;svg&#39;': 'svg',
            '&#39;text-to-image&#39;': 'text-to-image',
            '&#39;image-to-video&#39;': 'image-to-video',
            '&#39;text-to-speech&#39;': 'text-to-speech',
        },
        ('shape',): {
            '&#39;rectangle&#39;': 'rectangle',
            '&#39;circle&#39;': 'circle',
            '&#39;line&#39;': 'line',
        },
        ('volume_effect',): {
            '&#39;none&#39;': 'none',
            '&#39;fadeIn&#39;': 'fadeIn',
            '&#39;fadeOut&#39;': 'fadeOut',
            '&#39;fadeInFadeOut&#39;': 'fadeInFadeOut',
        },
        ('style',): {
            '&#39;minimal&#39;': 'minimal',
            '&#39;blockbuster&#39;': 'blockbuster',
            '&#39;vogue&#39;': 'vogue',
            '&#39;sketchy&#39;': 'sketchy',
            '&#39;skinny&#39;': 'skinny',
            '&#39;chunk&#39;': 'chunk',
            '&#39;chunkLight&#39;': 'chunkLight',
            '&#39;marker&#39;': 'marker',
            '&#39;future&#39;': 'future',
            '&#39;subtitle&#39;': 'subtitle',
        },
        ('effect',): {
            '&#39;none&#39;': 'none',
            '&#39;fadeIn&#39;': 'fadeIn',
            '&#39;fadeOut&#39;': 'fadeOut',
            '&#39;fadeInFadeOut&#39;': 'fadeInFadeOut',
        },
        ('position',): {
            '&#39;top&#39;': 'top',
            '&#39;topRight&#39;': 'topRight',
            '&#39;right&#39;': 'right',
            '&#39;bottomRight&#39;': 'bottomRight',
            '&#39;bottom&#39;': 'bottom',
            '&#39;bottomLeft&#39;': 'bottomLeft',
            '&#39;left&#39;': 'left',
            '&#39;topLeft&#39;': 'topLeft',
            '&#39;center&#39;': 'center',
        },
        ('size',): {
            '&#39;xx-small&#39;': 'xx-small',
            '&#39;x-small&#39;': 'x-small',
            '&#39;small&#39;': 'small',
            '&#39;medium&#39;': 'medium',
            '&#39;large&#39;': 'large',
            '&#39;x-large&#39;': 'x-large',
            '&#39;xx-large&#39;': 'xx-large',
        },
        ('aspect_ratio',): {
            '&#39;1:1&#39;': '1:1',
            '&#39;4:3&#39;': '4:3',
            '&#39;16:9&#39;': '16:9',
            '&#39;9:16&#39;': '9:16',
            '&#39;3:4&#39;': '3:4',
            '&#39;21:9&#39;': '21:9',
            '&#39;9:21&#39;': '9:21',
        },
    }

    validations = {
        ('src',): {
            'min_length': 1,
        },
        ('speed',): {
            'inclusive_maximum': 10,
            'inclusive_minimum': 0,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'type': (str,),  # noqa: E501
            'src': (str,),  # noqa: E501
            'text': (str,),  # noqa: E501
            'html': (str,),  # noqa: E501
            'shape': (str,),  # noqa: E501
            'prompt': (str,),  # noqa: E501
            'voice': (str,),  # noqa: E501
            'transcode': (bool,),  # noqa: E501
            'trim': (float,),  # noqa: E501
            'volume': (AudioAssetVolume,),  # noqa: E501
            'volume_effect': (str,),  # noqa: E501
            'speed': (float,),  # noqa: E501
            'crop': (Crop,),  # noqa: E501
            'chroma_key': (ChromaKey,),  # noqa: E501
            'width': (int,),  # noqa: E501
            'height': (int,),  # noqa: E501
            'font': (RichCaptionAssetFont,),  # noqa: E501
            'background': (str,),  # noqa: E501
            'alignment': (TextAlignment,),  # noqa: E501
            'stroke': (ShapeAssetStroke,),  # noqa: E501
            'animation': (RichCaptionAnimation,),  # noqa: E501
            'ellipsis': (str,),  # noqa: E501
            'style': (str,),  # noqa: E501
            'shadow': (RichTextShadow,),  # noqa: E501
            'border': (Border,),  # noqa: E501
            'padding': (RichCaptionAssetPadding,),  # noqa: E501
            'align': (RichTextAlignment,),  # noqa: E501
            'effect': (str,),  # noqa: E501
            'margin': (CaptionMargin,),  # noqa: E501
            'active': (RichCaptionActive,),  # noqa: E501
            'css': (str,),  # noqa: E501
            'position': (str,),  # noqa: E501
            'color': (str,),  # noqa: E501
            'size': (str,),  # noqa: E501
            'offset': (Offset,),  # noqa: E501
            'fill': (ShapeAssetFill,),  # noqa: E501
            'rectangle': (ShapeAssetRectangle,),  # noqa: E501
            'circle': (ShapeAssetCircle,),  # noqa: E501
            'line': (ShapeAssetLine,),  # noqa: E501
            'aspect_ratio': (str,),  # noqa: E501
            'language': (str,),  # noqa: E501
            'newscaster': (bool,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        lazy_import()
        val = {
            'audio': AudioAsset,
            'caption': CaptionAsset,
            'html': HtmlAsset,
            'image': ImageAsset,
            'image-to-video': ImageToVideoAsset,
            'luma': LumaAsset,
            'rich-caption': RichCaptionAsset,
            'rich-text': RichTextAsset,
            'shape': ShapeAsset,
            'svg': SvgAsset,
            'text': TextAsset,
            'text-to-image': TextToImageAsset,
            'text-to-speech': TextToSpeechAsset,
            'title': TitleAsset,
            'video': VideoAsset,
            'AudioAsset': AudioAsset,
            'CaptionAsset': CaptionAsset,
            'HtmlAsset': HtmlAsset,
            'ImageAsset': ImageAsset,
            'ImageToVideoAsset': ImageToVideoAsset,
            'LumaAsset': LumaAsset,
            'RichCaptionAsset': RichCaptionAsset,
            'RichTextAsset': RichTextAsset,
            'ShapeAsset': ShapeAsset,
            'SvgAsset': SvgAsset,
            'TextAsset': TextAsset,
            'TextToImageAsset': TextToImageAsset,
            'TextToSpeechAsset': TextToSpeechAsset,
            'TitleAsset': TitleAsset,
            'VideoAsset': VideoAsset,
        }
        if not val:
            return None
        return {'type': val}

    attribute_map = {
        'type': 'type',  # noqa: E501
        'src': 'src',  # noqa: E501
        'text': 'text',  # noqa: E501
        'html': 'html',  # noqa: E501
        'shape': 'shape',  # noqa: E501
        'prompt': 'prompt',  # noqa: E501
        'voice': 'voice',  # noqa: E501
        'transcode': 'transcode',  # noqa: E501
        'trim': 'trim',  # noqa: E501
        'volume': 'volume',  # noqa: E501
        'volume_effect': 'volumeEffect',  # noqa: E501
        'speed': 'speed',  # noqa: E501
        'crop': 'crop',  # noqa: E501
        'chroma_key': 'chromaKey',  # noqa: E501
        'width': 'width',  # noqa: E501
        'height': 'height',  # noqa: E501
        'font': 'font',  # noqa: E501
        'background': 'background',  # noqa: E501
        'alignment': 'alignment',  # noqa: E501
        'stroke': 'stroke',  # noqa: E501
        'animation': 'animation',  # noqa: E501
        'ellipsis': 'ellipsis',  # noqa: E501
        'style': 'style',  # noqa: E501
        'shadow': 'shadow',  # noqa: E501
        'border': 'border',  # noqa: E501
        'padding': 'padding',  # noqa: E501
        'align': 'align',  # noqa: E501
        'effect': 'effect',  # noqa: E501
        'margin': 'margin',  # noqa: E501
        'active': 'active',  # noqa: E501
        'css': 'css',  # noqa: E501
        'position': 'position',  # noqa: E501
        'color': 'color',  # noqa: E501
        'size': 'size',  # noqa: E501
        'offset': 'offset',  # noqa: E501
        'fill': 'fill',  # noqa: E501
        'rectangle': 'rectangle',  # noqa: E501
        'circle': 'circle',  # noqa: E501
        'line': 'line',  # noqa: E501
        'aspect_ratio': 'aspectRatio',  # noqa: E501
        'language': 'language',  # noqa: E501
        'newscaster': 'newscaster',  # noqa: E501
    }

    read_only_vars = {
    }

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Asset - a model defined in OpenAPI

        Keyword Args:
            type (str): The type of asset - set to `video` for videos.. defaults to 'video', must be one of ['video', 'image', 'text', 'rich-text', 'audio', 'luma', 'caption', 'rich-caption', 'html', 'title', 'shape', 'svg', 'text-to-image', 'image-to-video', 'text-to-speech', ]  # noqa: E501
            src (str): The image source URL. The URL must be publicly accessible or include credentials.
            text (str): The text to convert to speech.
            html (str): The HTML text string. See list of [supported HTML tags](https://shotstack.io/docs/guide/architecting-an-application/html-support/#supported-html-tags).
            shape (str): The shape to display.
            prompt (str): The instructions for modifying the image into a video sequence.
            voice (str): The voice to use for the text-to-speech conversion.
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            transcode (bool): Set to `true` to force re-encoding of the video during preprocessing. This can help resolve compatibility issues, fix rotation problems, synchronize audio, or convert formats. The video will be processed to ensure optimal compatibility with the rendering engine.. [optional]  # noqa: E501
            trim (float): The start trim point of the audio clip, in seconds (defaults to 0). Audio will start from the trim point. The audio will play until the file ends or the Clip length is reached.. [optional]  # noqa: E501
            volume (AudioAssetVolume): [optional]  # noqa: E501
            volume_effect (str): Preset volume effects to apply to the video asset <ul>   <li>`fadeIn` - fade volume in only</li>   <li>`fadeOut` - fade volume out only</li>   <li>`fadeInFadeOut` - fade volume in and out</li> </ul>. [optional]  # noqa: E501
            speed (float): Adjust the playback speed of the audio clip between 0 (paused) and 10 (10x normal speed), where 1 is normal speed (defaults to 1). Adjusting the speed will also adjust the duration of the clip and may require you to adjust the Clip length.. [optional]  # noqa: E501
            crop (Crop): [optional]  # noqa: E501
            chroma_key (ChromaKey): [optional]  # noqa: E501
            width (int): The width of the image in pixels.. [optional]  # noqa: E501
            height (int): The height of the image in pixels.. [optional]  # noqa: E501
            font (RichCaptionAssetFont): [optional]  # noqa: E501
            background (str): Apply a background color behind the text. Set the text color using hexadecimal color notation. Transparency is supported by setting the first two characters of the hex string (opposite to HTML),  i.e. #80ffffff will be white with 50% transparency. Omit to use transparent background.. [optional]  # noqa: E501
            alignment (TextAlignment): [optional]  # noqa: E501
            stroke (ShapeAssetStroke): [optional]  # noqa: E501
            animation (RichCaptionAnimation): [optional]  # noqa: E501
            ellipsis (str): The string to display when text overflows its bounding box. Set to an ellipsis character or custom string to indicate truncated text.. [optional]  # noqa: E501
            style (str): Uses a preset to apply font properties and styling to the title. <ul>   <li>`minimal`</li>   <li>`blockbuster`</li>   <li>`vogue`</li>   <li>`sketchy`</li>   <li>`skinny`</li>   <li>`chunk`</li>   <li>`chunkLight`</li>   <li>`marker`</li>   <li>`future`</li>   <li>`subtitle`</li> </ul>. [optional]  # noqa: E501
            shadow (RichTextShadow): [optional]  # noqa: E501
            border (Border): [optional]  # noqa: E501
            padding (RichCaptionAssetPadding): [optional]  # noqa: E501
            align (RichTextAlignment): [optional]  # noqa: E501
            effect (str): The effect to apply to the audio asset <ul>   <li>`fadeIn` - fade volume in only</li>   <li>`fadeOut` - fade volume out only</li>   <li>`fadeInFadeOut` - fade volume in and out</li> </ul>. [optional]  # noqa: E501
            margin (CaptionMargin): [optional]  # noqa: E501
            active (RichCaptionActive): [optional]  # noqa: E501
            css (str): The CSS text string to apply styling to the HTML. See list of  [support CSS properties](https://shotstack.io/docs/guide/architecting-an-application/html-support/#supported-css-properties).. [optional]  # noqa: E501
            position (str): Place the title in one of nine predefined positions of the viewport. <ul>   <li>`top` - top (center)</li>   <li>`topRight` - top right</li>   <li>`right` - right (center)</li>   <li>`bottomRight` - bottom right</li>   <li>`bottom` - bottom (center)</li>   <li>`bottomLeft` - bottom left</li>   <li>`left` - left (center)</li>   <li>`topLeft` - top left</li>   <li>`center` - center</li> </ul>. [optional]  # noqa: E501
            color (str): Set the text color using hexadecimal color notation. Transparency is supported by setting the first two characters of the hex string (opposite to HTML),  i.e. #80ffffff will be white with  50% transparency.. [optional]  # noqa: E501
            size (str): Set the relative size of the text using predefined sizes from xx-small to xx-large. <ul>   <li>`xx-small`</li>   <li>`x-small`</li>   <li>`small`</li>   <li>`medium`</li>   <li>`large`</li>   <li>`x-large`</li>   <li>`xx-large`</li> </ul>. [optional]  # noqa: E501
            offset (Offset): [optional]  # noqa: E501
            fill (ShapeAssetFill): [optional]  # noqa: E501
            rectangle (ShapeAssetRectangle): [optional]  # noqa: E501
            circle (ShapeAssetCircle): [optional]  # noqa: E501
            line (ShapeAssetLine): [optional]  # noqa: E501
            aspect_ratio (str): The aspect ratio (shape) of the video output.. [optional]  # noqa: E501
            language (str): The language code for the text-to-speech conversion.. [optional]  # noqa: E501
            newscaster (bool): Set the voice to newscaster mode.. [optional] if omitted the server will use the default value of False  # noqa: E501
        """

        type = kwargs.get('type', 'video')
        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)

        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
        '_composed_instances',
        '_var_name_to_model_instances',
        '_additional_properties_model_instances',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Asset - a model defined in OpenAPI

        Keyword Args:
            type (str): The type of asset - set to `video` for videos.. defaults to 'video', must be one of ['video', 'image', 'text', 'rich-text', 'audio', 'luma', 'caption', 'rich-caption', 'html', 'title', 'shape', 'svg', 'text-to-image', 'image-to-video', 'text-to-speech', ]  # noqa: E501
            src (str): The image source URL. The URL must be publicly accessible or include credentials.
            text (str): The text to convert to speech.
            html (str): The HTML text string. See list of [supported HTML tags](https://shotstack.io/docs/guide/architecting-an-application/html-support/#supported-html-tags).
            shape (str): The shape to display.
            prompt (str): The instructions for modifying the image into a video sequence.
            voice (str): The voice to use for the text-to-speech conversion.
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            transcode (bool): Set to `true` to force re-encoding of the video during preprocessing. This can help resolve compatibility issues, fix rotation problems, synchronize audio, or convert formats. The video will be processed to ensure optimal compatibility with the rendering engine.. [optional]  # noqa: E501
            trim (float): The start trim point of the audio clip, in seconds (defaults to 0). Audio will start from the trim point. The audio will play until the file ends or the Clip length is reached.. [optional]  # noqa: E501
            volume (AudioAssetVolume): [optional]  # noqa: E501
            volume_effect (str): Preset volume effects to apply to the video asset <ul>   <li>`fadeIn` - fade volume in only</li>   <li>`fadeOut` - fade volume out only</li>   <li>`fadeInFadeOut` - fade volume in and out</li> </ul>. [optional]  # noqa: E501
            speed (float): Adjust the playback speed of the audio clip between 0 (paused) and 10 (10x normal speed), where 1 is normal speed (defaults to 1). Adjusting the speed will also adjust the duration of the clip and may require you to adjust the Clip length.. [optional]  # noqa: E501
            crop (Crop): [optional]  # noqa: E501
            chroma_key (ChromaKey): [optional]  # noqa: E501
            width (int): The width of the image in pixels.. [optional]  # noqa: E501
            height (int): The height of the image in pixels.. [optional]  # noqa: E501
            font (RichCaptionAssetFont): [optional]  # noqa: E501
            background (str): Apply a background color behind the text. Set the text color using hexadecimal color notation. Transparency is supported by setting the first two characters of the hex string (opposite to HTML),  i.e. #80ffffff will be white with 50% transparency. Omit to use transparent background.. [optional]  # noqa: E501
            alignment (TextAlignment): [optional]  # noqa: E501
            stroke (ShapeAssetStroke): [optional]  # noqa: E501
            animation (RichCaptionAnimation): [optional]  # noqa: E501
            ellipsis (str): The string to display when text overflows its bounding box. Set to an ellipsis character or custom string to indicate truncated text.. [optional]  # noqa: E501
            style (str): Uses a preset to apply font properties and styling to the title. <ul>   <li>`minimal`</li>   <li>`blockbuster`</li>   <li>`vogue`</li>   <li>`sketchy`</li>   <li>`skinny`</li>   <li>`chunk`</li>   <li>`chunkLight`</li>   <li>`marker`</li>   <li>`future`</li>   <li>`subtitle`</li> </ul>. [optional]  # noqa: E501
            shadow (RichTextShadow): [optional]  # noqa: E501
            border (Border): [optional]  # noqa: E501
            padding (RichCaptionAssetPadding): [optional]  # noqa: E501
            align (RichTextAlignment): [optional]  # noqa: E501
            effect (str): The effect to apply to the audio asset <ul>   <li>`fadeIn` - fade volume in only</li>   <li>`fadeOut` - fade volume out only</li>   <li>`fadeInFadeOut` - fade volume in and out</li> </ul>. [optional]  # noqa: E501
            margin (CaptionMargin): [optional]  # noqa: E501
            active (RichCaptionActive): [optional]  # noqa: E501
            css (str): The CSS text string to apply styling to the HTML. See list of  [support CSS properties](https://shotstack.io/docs/guide/architecting-an-application/html-support/#supported-css-properties).. [optional]  # noqa: E501
            position (str): Place the title in one of nine predefined positions of the viewport. <ul>   <li>`top` - top (center)</li>   <li>`topRight` - top right</li>   <li>`right` - right (center)</li>   <li>`bottomRight` - bottom right</li>   <li>`bottom` - bottom (center)</li>   <li>`bottomLeft` - bottom left</li>   <li>`left` - left (center)</li>   <li>`topLeft` - top left</li>   <li>`center` - center</li> </ul>. [optional]  # noqa: E501
            color (str): Set the text color using hexadecimal color notation. Transparency is supported by setting the first two characters of the hex string (opposite to HTML),  i.e. #80ffffff will be white with  50% transparency.. [optional]  # noqa: E501
            size (str): Set the relative size of the text using predefined sizes from xx-small to xx-large. <ul>   <li>`xx-small`</li>   <li>`x-small`</li>   <li>`small`</li>   <li>`medium`</li>   <li>`large`</li>   <li>`x-large`</li>   <li>`xx-large`</li> </ul>. [optional]  # noqa: E501
            offset (Offset): [optional]  # noqa: E501
            fill (ShapeAssetFill): [optional]  # noqa: E501
            rectangle (ShapeAssetRectangle): [optional]  # noqa: E501
            circle (ShapeAssetCircle): [optional]  # noqa: E501
            line (ShapeAssetLine): [optional]  # noqa: E501
            aspect_ratio (str): The aspect ratio (shape) of the video output.. [optional]  # noqa: E501
            language (str): The language code for the text-to-speech conversion.. [optional]  # noqa: E501
            newscaster (bool): Set the voice to newscaster mode.. [optional] if omitted the server will use the default value of False  # noqa: E501
        """

        type = kwargs.get('type', 'video')
        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")

    @cached_property
    def _composed_schemas():
        # we need this here to make our import statements work
        # we must store _composed_schemas in here so the code is only run
        # when we invoke this method. If we kept this at the class
        # level we would get an error because the class level
        # code would be run when this module is imported, and these composed
        # classes don't exist yet because their module has not finished
        # loading
        lazy_import()
        return {
          'anyOf': [
          ],
          'allOf': [
          ],
          'oneOf': [
              AudioAsset,
              CaptionAsset,
              HtmlAsset,
              ImageAsset,
              ImageToVideoAsset,
              LumaAsset,
              RichCaptionAsset,
              RichTextAsset,
              ShapeAsset,
              SvgAsset,
              TextAsset,
              TextToImageAsset,
              TextToSpeechAsset,
              TitleAsset,
              VideoAsset,
          ],
        }
