"""
    Shotstack

    Official Python SDK for the Shotstack Cloud Video Editing API

    The version of the OpenAPI document: v1
    Contact: pypi@shotstack.io
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from shotstack_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from shotstack_sdk.exceptions import ApiAttributeError



class Transition(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('var_in',): {
            '&#39;none&#39;': 'none',
            '&#39;fade&#39;': 'fade',
            '&#39;fadeSlow&#39;': 'fadeSlow',
            '&#39;fadeFast&#39;': 'fadeFast',
            '&#39;reveal&#39;': 'reveal',
            '&#39;revealSlow&#39;': 'revealSlow',
            '&#39;revealFast&#39;': 'revealFast',
            '&#39;wipeLeft&#39;': 'wipeLeft',
            '&#39;wipeLeftSlow&#39;': 'wipeLeftSlow',
            '&#39;wipeLeftFast&#39;': 'wipeLeftFast',
            '&#39;wipeRight&#39;': 'wipeRight',
            '&#39;wipeRightSlow&#39;': 'wipeRightSlow',
            '&#39;wipeRightFast&#39;': 'wipeRightFast',
            '&#39;slideLeft&#39;': 'slideLeft',
            '&#39;slideLeftSlow&#39;': 'slideLeftSlow',
            '&#39;slideLeftFast&#39;': 'slideLeftFast',
            '&#39;slideRight&#39;': 'slideRight',
            '&#39;slideRightSlow&#39;': 'slideRightSlow',
            '&#39;slideRightFast&#39;': 'slideRightFast',
            '&#39;slideUp&#39;': 'slideUp',
            '&#39;slideUpSlow&#39;': 'slideUpSlow',
            '&#39;slideUpFast&#39;': 'slideUpFast',
            '&#39;slideDown&#39;': 'slideDown',
            '&#39;slideDownSlow&#39;': 'slideDownSlow',
            '&#39;slideDownFast&#39;': 'slideDownFast',
            '&#39;carouselLeft&#39;': 'carouselLeft',
            '&#39;carouselLeftSlow&#39;': 'carouselLeftSlow',
            '&#39;carouselLeftFast&#39;': 'carouselLeftFast',
            '&#39;carouselRight&#39;': 'carouselRight',
            '&#39;carouselRightSlow&#39;': 'carouselRightSlow',
            '&#39;carouselRightFast&#39;': 'carouselRightFast',
            '&#39;carouselUp&#39;': 'carouselUp',
            '&#39;carouselUpSlow&#39;': 'carouselUpSlow',
            '&#39;carouselUpFast&#39;': 'carouselUpFast',
            '&#39;carouselDown&#39;': 'carouselDown',
            '&#39;carouselDownSlow&#39;': 'carouselDownSlow',
            '&#39;carouselDownFast&#39;': 'carouselDownFast',
            '&#39;shuffleTopRight&#39;': 'shuffleTopRight',
            '&#39;shuffleTopRightSlow&#39;': 'shuffleTopRightSlow',
            '&#39;shuffleTopRightFast&#39;': 'shuffleTopRightFast',
            '&#39;shuffleRightTop&#39;': 'shuffleRightTop',
            '&#39;shuffleRightTopSlow&#39;': 'shuffleRightTopSlow',
            '&#39;shuffleRightTopFast&#39;': 'shuffleRightTopFast',
            '&#39;shuffleRightBottom&#39;': 'shuffleRightBottom',
            '&#39;shuffleRightBottomSlow&#39;': 'shuffleRightBottomSlow',
            '&#39;shuffleRightBottomFast&#39;': 'shuffleRightBottomFast',
            '&#39;shuffleBottomRight&#39;': 'shuffleBottomRight',
            '&#39;shuffleBottomRightSlow&#39;': 'shuffleBottomRightSlow',
            '&#39;shuffleBottomRightFast&#39;': 'shuffleBottomRightFast',
            '&#39;shuffleBottomLeft&#39;': 'shuffleBottomLeft',
            '&#39;shuffleBottomLeftSlow&#39;': 'shuffleBottomLeftSlow',
            '&#39;shuffleBottomLeftFast&#39;': 'shuffleBottomLeftFast',
            '&#39;shuffleLeftBottom&#39;': 'shuffleLeftBottom',
            '&#39;shuffleLeftBottomSlow&#39;': 'shuffleLeftBottomSlow',
            '&#39;shuffleLeftBottomFast&#39;': 'shuffleLeftBottomFast',
            '&#39;shuffleLeftTop&#39;': 'shuffleLeftTop',
            '&#39;shuffleLeftTopSlow&#39;': 'shuffleLeftTopSlow',
            '&#39;shuffleLeftTopFast&#39;': 'shuffleLeftTopFast',
            '&#39;shuffleTopLeft&#39;': 'shuffleTopLeft',
            '&#39;shuffleTopLeftSlow&#39;': 'shuffleTopLeftSlow',
            '&#39;shuffleTopLeftFast&#39;': 'shuffleTopLeftFast',
            '&#39;zoom&#39;': 'zoom',
        },
        ('out',): {
            '&#39;none&#39;': 'none',
            '&#39;fade&#39;': 'fade',
            '&#39;fadeSlow&#39;': 'fadeSlow',
            '&#39;fadeFast&#39;': 'fadeFast',
            '&#39;reveal&#39;': 'reveal',
            '&#39;revealSlow&#39;': 'revealSlow',
            '&#39;revealFast&#39;': 'revealFast',
            '&#39;wipeLeft&#39;': 'wipeLeft',
            '&#39;wipeLeftSlow&#39;': 'wipeLeftSlow',
            '&#39;wipeLeftFast&#39;': 'wipeLeftFast',
            '&#39;wipeRight&#39;': 'wipeRight',
            '&#39;wipeRightSlow&#39;': 'wipeRightSlow',
            '&#39;wipeRightFast&#39;': 'wipeRightFast',
            '&#39;slideLeft&#39;': 'slideLeft',
            '&#39;slideLeftSlow&#39;': 'slideLeftSlow',
            '&#39;slideLeftFast&#39;': 'slideLeftFast',
            '&#39;slideRight&#39;': 'slideRight',
            '&#39;slideRightSlow&#39;': 'slideRightSlow',
            '&#39;slideRightFast&#39;': 'slideRightFast',
            '&#39;slideUp&#39;': 'slideUp',
            '&#39;slideUpSlow&#39;': 'slideUpSlow',
            '&#39;slideUpFast&#39;': 'slideUpFast',
            '&#39;slideDown&#39;': 'slideDown',
            '&#39;slideDownSlow&#39;': 'slideDownSlow',
            '&#39;slideDownFast&#39;': 'slideDownFast',
            '&#39;carouselLeft&#39;': 'carouselLeft',
            '&#39;carouselLeftSlow&#39;': 'carouselLeftSlow',
            '&#39;carouselLeftFast&#39;': 'carouselLeftFast',
            '&#39;carouselRight&#39;': 'carouselRight',
            '&#39;carouselRightSlow&#39;': 'carouselRightSlow',
            '&#39;carouselRightFast&#39;': 'carouselRightFast',
            '&#39;carouselUp&#39;': 'carouselUp',
            '&#39;carouselUpSlow&#39;': 'carouselUpSlow',
            '&#39;carouselUpFast&#39;': 'carouselUpFast',
            '&#39;carouselDown&#39;': 'carouselDown',
            '&#39;carouselDownSlow&#39;': 'carouselDownSlow',
            '&#39;carouselDownFast&#39;': 'carouselDownFast',
            '&#39;shuffleTopRight&#39;': 'shuffleTopRight',
            '&#39;shuffleTopRightSlow&#39;': 'shuffleTopRightSlow',
            '&#39;shuffleTopRightFast&#39;': 'shuffleTopRightFast',
            '&#39;shuffleRightTop&#39;': 'shuffleRightTop',
            '&#39;shuffleRightTopSlow&#39;': 'shuffleRightTopSlow',
            '&#39;shuffleRightTopFast&#39;': 'shuffleRightTopFast',
            '&#39;shuffleRightBottom&#39;': 'shuffleRightBottom',
            '&#39;shuffleRightBottomSlow&#39;': 'shuffleRightBottomSlow',
            '&#39;shuffleRightBottomFast&#39;': 'shuffleRightBottomFast',
            '&#39;shuffleBottomRight&#39;': 'shuffleBottomRight',
            '&#39;shuffleBottomRightSlow&#39;': 'shuffleBottomRightSlow',
            '&#39;shuffleBottomRightFast&#39;': 'shuffleBottomRightFast',
            '&#39;shuffleBottomLeft&#39;': 'shuffleBottomLeft',
            '&#39;shuffleBottomLeftSlow&#39;': 'shuffleBottomLeftSlow',
            '&#39;shuffleBottomLeftFast&#39;': 'shuffleBottomLeftFast',
            '&#39;shuffleLeftBottom&#39;': 'shuffleLeftBottom',
            '&#39;shuffleLeftBottomSlow&#39;': 'shuffleLeftBottomSlow',
            '&#39;shuffleLeftBottomFast&#39;': 'shuffleLeftBottomFast',
            '&#39;shuffleLeftTop&#39;': 'shuffleLeftTop',
            '&#39;shuffleLeftTopSlow&#39;': 'shuffleLeftTopSlow',
            '&#39;shuffleLeftTopFast&#39;': 'shuffleLeftTopFast',
            '&#39;shuffleTopLeft&#39;': 'shuffleTopLeft',
            '&#39;shuffleTopLeftSlow&#39;': 'shuffleTopLeftSlow',
            '&#39;shuffleTopLeftFast&#39;': 'shuffleTopLeftFast',
            '&#39;zoom&#39;': 'zoom',
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'var_in': (str,),  # noqa: E501
            'out': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'var_in': 'in',  # noqa: E501
        'out': 'out',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Transition - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            var_in (str): The transition in. Available transitions are:   <ul>     <li>`fade` - fade in</li>     <li>`reveal` - reveal from left to right</li>     <li>`wipeLeft` - fade across screen to the left</li>     <li>`wipeRight` - fade across screen to the right</li>     <li>`slideLeft` - move slightly left and fade in</li>     <li>`slideRight` - move slightly right and fade in</li>     <li>`slideUp` - move slightly up and fade in</li>     <li>`slideDown` - move slightly down and fade in</li>     <li>`carouselLeft` - slide in from right to left</li>     <li>`carouselRight` - slide in from left to right</li>     <li>`carouselUp` - slide in from bottom to top</li>     <li>`carouselDown` - slide in from top to bottom</li>     <li>`shuffleTopRight` - rotate in from top right</li>     <li>`shuffleRightTop` - rotate in from right top</li>     <li>`shuffleRightBottom` - rotate in from right bottom</li>     <li>`shuffleBottomRight` - rotate in from bottom right</li>     <li>`shuffleBottomLeft` - rotate in from bottom left</li>     <li>`shuffleLeftBottom` - rotate in from left bottom</li>     <li>`shuffleLeftTop` - rotate in from left top</li>     <li>`shuffleTopLeft` - rotate in from top left</li>     <li>`zoom` - fast zoom in</li>   </ul> The transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.. [optional]  # noqa: E501
            out (str): The transition out. Available transitions are:   <ul>     <li>`fade` - fade out</li>     <li>`reveal` - reveal from right to left</li>     <li>`wipeLeft` - fade across screen to the left</li>     <li>`wipeRight` - fade across screen to the right</li>     <li>`slideLeft` - move slightly left and fade out</li>     <li>`slideRight` - move slightly right and fade out</li>     <li>`slideUp` - move slightly up and fade out</li>     <li>`slideDown` - move slightly down and fade out</li>     <li>`carouselLeft` - slide out from right to left</li>     <li>`carouselRight` - slide out from left to right</li>     <li>`carouselUp` - slide out from bottom to top</li>     <li>`carouselDown` - slide out from top  to bottom</li>     <li>`shuffleTopRight` - rotate out from top right</li>     <li>`shuffleRightTop` - rotate out from right top</li>     <li>`shuffleRightBottom` - rotate out from right bottom</li>     <li>`shuffleBottomRight` - rotate out from bottom right</li>     <li>`shuffleBottomLeft` - rotate out from bottom left</li>     <li>`shuffleLeftBottom` - rotate out from left bottom</li>     <li>`shuffleLeftTop` - rotate out from left top</li>     <li>`shuffleTopLeft` - rotate out from top left</li>     <li>`zoom` - fast zoom out</li>   </ul> The transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Transition - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            var_in (str): The transition in. Available transitions are:   <ul>     <li>`fade` - fade in</li>     <li>`reveal` - reveal from left to right</li>     <li>`wipeLeft` - fade across screen to the left</li>     <li>`wipeRight` - fade across screen to the right</li>     <li>`slideLeft` - move slightly left and fade in</li>     <li>`slideRight` - move slightly right and fade in</li>     <li>`slideUp` - move slightly up and fade in</li>     <li>`slideDown` - move slightly down and fade in</li>     <li>`carouselLeft` - slide in from right to left</li>     <li>`carouselRight` - slide in from left to right</li>     <li>`carouselUp` - slide in from bottom to top</li>     <li>`carouselDown` - slide in from top to bottom</li>     <li>`shuffleTopRight` - rotate in from top right</li>     <li>`shuffleRightTop` - rotate in from right top</li>     <li>`shuffleRightBottom` - rotate in from right bottom</li>     <li>`shuffleBottomRight` - rotate in from bottom right</li>     <li>`shuffleBottomLeft` - rotate in from bottom left</li>     <li>`shuffleLeftBottom` - rotate in from left bottom</li>     <li>`shuffleLeftTop` - rotate in from left top</li>     <li>`shuffleTopLeft` - rotate in from top left</li>     <li>`zoom` - fast zoom in</li>   </ul> The transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.. [optional]  # noqa: E501
            out (str): The transition out. Available transitions are:   <ul>     <li>`fade` - fade out</li>     <li>`reveal` - reveal from right to left</li>     <li>`wipeLeft` - fade across screen to the left</li>     <li>`wipeRight` - fade across screen to the right</li>     <li>`slideLeft` - move slightly left and fade out</li>     <li>`slideRight` - move slightly right and fade out</li>     <li>`slideUp` - move slightly up and fade out</li>     <li>`slideDown` - move slightly down and fade out</li>     <li>`carouselLeft` - slide out from right to left</li>     <li>`carouselRight` - slide out from left to right</li>     <li>`carouselUp` - slide out from bottom to top</li>     <li>`carouselDown` - slide out from top  to bottom</li>     <li>`shuffleTopRight` - rotate out from top right</li>     <li>`shuffleRightTop` - rotate out from right top</li>     <li>`shuffleRightBottom` - rotate out from right bottom</li>     <li>`shuffleBottomRight` - rotate out from bottom right</li>     <li>`shuffleBottomLeft` - rotate out from bottom left</li>     <li>`shuffleLeftBottom` - rotate out from left bottom</li>     <li>`shuffleLeftTop` - rotate out from left top</li>     <li>`shuffleTopLeft` - rotate out from top left</li>     <li>`zoom` - fast zoom out</li>   </ul> The transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
