"""
    Shotstack

    Official Python SDK for the Shotstack Cloud Video Editing API

    The version of the OpenAPI document: v1
    Contact: pypi@shotstack.io
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from shotstack_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from shotstack_sdk.exceptions import ApiAttributeError



class Tween(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('interpolation',): {
            '&#39;linear&#39;': 'linear',
            '&#39;bezier&#39;': 'bezier',
            '&#39;constant&#39;': 'constant',
        },
        ('easing',): {
            '&#39;ease&#39;': 'ease',
            '&#39;easeIn&#39;': 'easeIn',
            '&#39;easeOut&#39;': 'easeOut',
            '&#39;easeInOut&#39;': 'easeInOut',
            '&#39;easeInQuad&#39;': 'easeInQuad',
            '&#39;easeInCubic&#39;': 'easeInCubic',
            '&#39;easeInQuart&#39;': 'easeInQuart',
            '&#39;easeInQuint&#39;': 'easeInQuint',
            '&#39;easeInSine&#39;': 'easeInSine',
            '&#39;easeInExpo&#39;': 'easeInExpo',
            '&#39;easeInCirc&#39;': 'easeInCirc',
            '&#39;easeInBack&#39;': 'easeInBack',
            '&#39;easeOutQuad&#39;': 'easeOutQuad',
            '&#39;easeOutCubic&#39;': 'easeOutCubic',
            '&#39;easeOutQuart&#39;': 'easeOutQuart',
            '&#39;easeOutQuint&#39;': 'easeOutQuint',
            '&#39;easeOutSine&#39;': 'easeOutSine',
            '&#39;easeOutExpo&#39;': 'easeOutExpo',
            '&#39;easeOutCirc&#39;': 'easeOutCirc',
            '&#39;easeOutBack&#39;': 'easeOutBack',
            '&#39;easeInOutQuad&#39;': 'easeInOutQuad',
            '&#39;easeInOutCubic&#39;': 'easeInOutCubic',
            '&#39;easeInOutQuart&#39;': 'easeInOutQuart',
            '&#39;easeInOutQuint&#39;': 'easeInOutQuint',
            '&#39;easeInOutSine&#39;': 'easeInOutSine',
            '&#39;easeInOutExpo&#39;': 'easeInOutExpo',
            '&#39;easeInOutCirc&#39;': 'easeInOutCirc',
            '&#39;easeInOutBack&#39;': 'easeInOutBack',
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'var_from': (object,),  # noqa: E501
            'to': (object,),  # noqa: E501
            'start': (float,),  # noqa: E501
            'length': (float,),  # noqa: E501
            'interpolation': (str,),  # noqa: E501
            'easing': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'var_from': 'from',  # noqa: E501
        'to': 'to',  # noqa: E501
        'start': 'start',  # noqa: E501
        'length': 'length',  # noqa: E501
        'interpolation': 'interpolation',  # noqa: E501
        'easing': 'easing',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Tween - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            var_from (object): The initial property value at the start of the animation.. [optional]  # noqa: E501
            to (object): The final property value at the end of the animation.. [optional]  # noqa: E501
            start (float): The time in seconds when the animation starts, relative to the clip, not the timeline.. [optional]  # noqa: E501
            length (float): The duration of the animation in seconds.. [optional]  # noqa: E501
            interpolation (str): The interpolation method to use for the animation. Available options are: <ul>   <li>`linear` - a linear interpolation between the start and end values.</li>   <li>`bezier` - a bezier curve interpolation between the start and end values.</li>   <li>`constant` - an interpolation where the property instantly jumps from the start to the end value, without any gradual transition.</li> </ul>. [optional]  # noqa: E501
            easing (str): The easing function to use for the animation. Easing controls the rate of change of the animated value, allowing for more natural motion by speeding up or slowing down the animation at different points. Only applicable if interpolation is set to `bezier`.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Tween - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            var_from (object): The initial property value at the start of the animation.. [optional]  # noqa: E501
            to (object): The final property value at the end of the animation.. [optional]  # noqa: E501
            start (float): The time in seconds when the animation starts, relative to the clip, not the timeline.. [optional]  # noqa: E501
            length (float): The duration of the animation in seconds.. [optional]  # noqa: E501
            interpolation (str): The interpolation method to use for the animation. Available options are: <ul>   <li>`linear` - a linear interpolation between the start and end values.</li>   <li>`bezier` - a bezier curve interpolation between the start and end values.</li>   <li>`constant` - an interpolation where the property instantly jumps from the start to the end value, without any gradual transition.</li> </ul>. [optional]  # noqa: E501
            easing (str): The easing function to use for the animation. Easing controls the rate of change of the animated value, allowing for more natural motion by speeding up or slowing down the animation at different points. Only applicable if interpolation is set to `bezier`.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
