# flake8: noqa

"""
    Shotstack

    Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file  location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are two main API's, one for editing and generating assets (Edit API) and one for managing hosted assets (Serve API).  The Edit API base URL is: <b>https://api.shotstack.io/{version}</b>  The Serve API base URL is: <b>https://api.shotstack.io/serve/{version}</b>   # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from shotstack_sdk.api_client import ApiClient

# import Configuration
from shotstack_sdk.configuration import Configuration

# import exceptions
from shotstack_sdk.exceptions import OpenApiException
from shotstack_sdk.exceptions import ApiAttributeError
from shotstack_sdk.exceptions import ApiTypeError
from shotstack_sdk.exceptions import ApiValueError
from shotstack_sdk.exceptions import ApiKeyError
from shotstack_sdk.exceptions import ApiException
